version: '3'
services:
  test:
    container_name: test-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - 666:666
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    # volumes:
    #   - ./templates:/etc/nginx/templates
    volumes:
      - .\nginx\default .conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./.env

volumes:
  mongo-db: