version: '3'
services:
  test:
    container_name: test-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - 666:666
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./.env

volumes:
  mongo-db: